apiVersion: apps/v1
kind: Deployment
metadata:
  name: ner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ner-service
  template:
    metadata:
      labels:
        app: ner-service
    spec:
      containers:
      - name: ner-container
        # Image NER Service 
        image: asia-southeast2-docker.pkg.dev/shipvue-project/shipvue-repo/ner-service:v1
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ner-service # DNS Internal 
spec:
  selector:
    app: ner-service
  ports:
    - protocol: TCP
      port: 80        # Agent akan memanggil port 80
      targetPort: 8000 # Diteruskan ke port 8000 container
  type: ClusterIP     # Hanya bisa diakses dari dalam cluster